# Generated by Django 4.0.3 on 2022-03-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, unique=True)),
                ('team_logo', models.ImageField(upload_to='teamimages')),
                ('team_state', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
