# Generated by Django 4.0.3 on 2022-03-10 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matches', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('fifties', models.CharField(max_length=50)),
                ('hundreds', models.CharField(max_length=50)),
                ('highest_score', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='playerhistory', serialize=False, to='cricket.history')),
                ('player_first_name', models.CharField(max_length=100)),
                ('player_last_name', models.CharField(max_length=100)),
                ('player_jersey_number', models.IntegerField(unique=True)),
                ('player_country', models.CharField(max_length=50)),
                ('player_image', models.ImageField(upload_to='playerimages')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iplteam', to='cricket.team')),
            ],
            bases=('cricket.history',),
        ),
    ]
