# Generated by Django 4.0.3 on 2022-03-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0002_history_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='matches',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='history',
            name='runs',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_jersey_number',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
