# Generated by Django 4.0.3 on 2022-03-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0003_alter_history_matches_alter_history_runs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_role',
            field=models.CharField(default='Batsman', max_length=50),
        ),
    ]
