# Generated by Django 4.0.3 on 2022-03-31 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0005_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='iplteampoint', serialize=False, to='cricket.team')),
                ('win', models.PositiveIntegerField()),
                ('defeat', models.PositiveIntegerField()),
                ('point', models.PositiveIntegerField()),
            ],
        ),
    ]
