# Generated by Django 4.0.3 on 2022-03-31 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricket', '0006_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='match_counter',
            field=models.PositiveIntegerField(default=7),
        ),
    ]
